# Generated by Django 4.1.5 on 2023-02-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2001-05-27'),
            preserve_default=False,
        ),
    ]
